### ISSUE TITLE
loading google-charts-node in ES6 module

### ISSUE THREAD

**Issue by otatar** [typpo/google-charts-node#10]
Hi there,

in my project I am using ES6 modules, how to import google-charts-node (it is commonJS)? I have tried this script and it does generate blank(empty) PNG:

`import { writeFileSync } from 'fs';
import GoogleChartsNode from 'google-charts-node';
(async () => {
    const image = await GoogleChartsNode.render(generateBarChart, {
      width: 400,
      height: 300,
    });
  
    writeFileSync('google-chart.png', image);
  })();

function generateBarChart() {

      var data = google.visualization.arrayToDataTable([
        ['City', '2010 Population'],
        ['New York City, NY', 8175000],
        ['Los Angeles, CA', 3792000],
        ['Chicago, IL', 2695000],
        ['Houston, TX', 2099000],
        ['Philadelphia, PA', 1526000],
      ]);
    
      var options = {
        title: 'Population of Largest U.S. Cities',
        chartArea: { width: '50%' },
        hAxis: {
          title: 'Total Population',
          minValue: 0,
        },
        vAxis: {
          title: 'City',
        },
      };

      const chart = new google.visualization.BarChart(container);
      chart.draw(data, options);
  }
`

**Comment by otatar** [comment]
Strange thing, this happened even when I was using CommonJS. It turned out that I used function name other than drawChart as you can see:  generateBarChart. As soon as I renamed function to drawChart it worked! 
Is this a bug, or a function has to have name: drawChart()

**Comment by typpo** [comment]
Hi @otatar, thanks for the report.  This looks like a bug.  I will fix this soon.  For now, you can bypass by naming your function `drawChart`.

**Comment by typpo** [comment]
This should be fixed in v1.0.4
