### ISSUE TITLE
offline version

### ISSUE THREAD

**Issue by kpetrow** [typpo/google-charts-node#12]
Is there any chance that you know of an offline version?  Searching far and wide for a backend graphing library that doesnt require calls to outside services

**Comment by typpo** [comment]
Google [prohibits](https://developers.google.com/chart/interactive/faq) use of Google Charts offline

> Can I use charts offline?
> Your users' computers must have access to https://www.gstatic.com/charts/loader.js in order to use the interactive features of Google Charts. This is because the visualization libraries that your page requires are loaded dynamically before you use them. The code for loading the appropriate library is part of the included script, and is called when you invoke the google.charts.load() method. Our [terms of service](https://developers.google.com/chart/terms) do not allow you to download the google.charts.load or google.visualization code to use offline.

For an offline charting alternative, you could consider something like [QuickChart](https://github.com/typpo/quickchart)
