### ISSUE TITLE
"Failed to launch Browser process" error 

### ISSUE THREAD

**Issue by saivigneshs** [typpo/google-charts-node#13]
Hi all, I'm trying to deploy a nodeJS service to cloudfoundry. It has a "google-charts-node" dependency. The app crashes with the following error, ERR /home/vcap/deps/0/node_modules/google-charts-node/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such f
ile or directory

![image](https://user-images.githubusercontent.com/78722129/171874486-df6a6faf-f97e-4ba1-b7f6-05ae1a8f6b43.png)

Has anyone come across such error. Suggestions are welcome. Thank you!

**Comment by typpo** [comment]
Your environment on Cloud Foundry is missing dependencies, specifically puppeteer dependencies.  You can learn more about dependency troubleshooting in the puppeteer docs: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

Hope this helps!
