### ISSUE TITLE
Not working on azure cloud function

### ISSUE THREAD

**Issue by bensonkariuki** [typpo/google-charts-node#18]
When trying to deploy a working implementation that works locally on a windows environment, it does not run as a cloud function. The following error is being triggered 

```Error: Could not find browser revision 756035. Run "npm install" or "yarn install" to download a browser binary.2023-03-13T13:08:21Z [Information] at ChromeLauncher.launch (C:\home\site\wwwroot\node_modules\google-charts-node\node_modules\puppeteer\lib\Launcher.js:81:23)2023-03-13T13:08:21Z [Information] at async Object.renderGoogleChart [as render] (C:\home\site\wwwroot\node_modules\google-charts-node\lib\render.js:23:19)2023-03-13T13:08:21Z [Information] at async createChart (C:\home\site\wwwroot\TimerTrigger1\helpers\donut_chart.js:59:19)2023-03-13T13:08:21Z [Information] at async getDonutChartData (C:\home\site\wwwroot\TimerTrigger1\helpers\donut_chart.js:122:13)2023-03-13T13:08:21Z [Information] at async processReports (C:\home\site\wwwroot\TimerTrigger1\helpers\index.js:56:33)2023-03-13T13:08:21Z [Information] at async module.exports (C:\home\site\wwwroot\TimerTrigger1\index.js:9:5)```

It seems that the code is trying to launch Puppeteer with a specific browser revision (756035), but the binary for that revision is not available on your system.

You can try running "npm install" or "yarn install" to download the necessary browser binary. This will install the required dependencies and should solve the issue.

If that doesn't work, you can also try passing a different browser revision to Puppeteer by setting the "executablePath" option. For example:

javascript

const puppeteer = require('puppeteer-core');

const browser = await puppeteer.launch({
  executablePath: '/path/to/chrome',
});

**Comment by typpo** [comment]
Hi @bensonkariuki,

Please refer to the puppeteer docs, specifically "Could not find expected browser locally".  There are some envars you should set (or you can create a `.puppeteerrc.cjs`): https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#could-not-find-expected-browser-locally

**Comment by bensonkariuki** [comment]
@typpo , thank you for your feedback. I'll check it out. I can see you're using puppeteer version 4.0.0. Could you update this to the latest version i.e. puppeteer v19.7.5 . Great work on this project.

**Comment by typpo** [comment]
Just released version 2.0.0, which uses the latest puppeteer :) Hope this helps
