### ISSUE TITLE
Update Puppeteer library

### ISSUE THREAD

**Issue by vzelenko** [typpo/google-charts-node#26]
Hey, great project!

## Problem Description
 
This project is using an outdated version of Puppeteer.  Looks like you are just passing the options to the underlying library, so it should be a simple `npm audit fix --force` to correct it.

## Solution

1. `npm audit fix --force`.
2. Add a warning to the main README file for users to check options passed to this library.

## Additional Details

Call to `npm audit` generates the following output on our project:

```sh
# npm audit report

ws  8.0.0 - 8.17.0
Severity: high
ws affected by a DoS when handling a request with many HTTP headers - https://github.com/advisories/GHSA-3h5v-q93c-6h6q
fix available via `npm audit fix --force`
Will install google-charts-node@1.1.0, which is a breaking change
node_modules/google-charts-node/node_modules/ws
  puppeteer-core  11.0.0 - 22.11.1
  Depends on vulnerable versions of ws
  node_modules/google-charts-node/node_modules/puppeteer-core
    puppeteer  18.2.0 - 22.11.1
    Depends on vulnerable versions of puppeteer-core
    node_modules/google-charts-node/node_modules/puppeteer
      google-charts-node  >=2.0.0
      Depends on vulnerable versions of puppeteer
      node_modules/google-charts-node

4 high severity vulnerabilities
```

**Comment by vzelenko** [comment]
Happy to add a PR for this fix, lmk.

**Comment by typpo** [comment]
Hi Vlad,

Would be glad to accept a PR for this!

**Comment by vzelenko** [comment]
Here you go.  https://github.com/typpo/google-charts-node/pull/27
