### ISSUE TITLE
Problem with google.visualization not defined

### ISSUE THREAD

**Issue by wpride** [typpo/google-charts-node#3]
👋 This is possibly a very silly question, but where is the `google` module in `google.visualization.arrayToDataTable` supposed to be imported from? Seems like this usually comes from:

```
<script src="https://www.gstatic.com/charts/loader.js"></script>
```

But of course this isn't available on the backend. Am I supposed to load this some other way?

**Comment by typpo** [comment]
Hi William, the loader.js script is loaded as part of the rendering process via puppeteer.  Which means `google.visualization.arrayToDataTable` is available to you in the renderer, even if it's not imported in your Javascript.  The `drawChart` function that you provide is converted to string and passed to the renderer.  You don't have to import any google library.

If the reference to `google.visualization.arrayToDataTable` is throwing off your IDE or static type checker, you may turn the whole thing into a Javascript string and pass it to the `GoogleChartsNode.render` function.  I just added an example of this [here](https://github.com/typpo/google-charts-node/blob/master/examples/chart_as_string.js).

Let me know if I can further clarify anything for you.

**Comment by wpride** [comment]
Aha, got it. Thank you for the prompt response. Excellent library by the way 😄

**Comment by typpo** [comment]
No problem!  Definitely let me know if you have other questions or run into limitations :)
