### ISSUE TITLE
Problem with google is not defined

### ISSUE THREAD

**Issue by aow73320** [typpo/google-charts-node#4]
At the beginning every thing work,no problem,
then suddenly this error just show up,
so i dont know what happened

` UnhandledPromiseRejectionWarning: ReferenceError: google is not defined`

**Comment by aow73320** [comment]
sor i know what wrong,
when i try to send something into drawChart(arg)
arg it will lead to error

`const image = await GoogleChartsNode.render(drawChart(arg), {
      packages: ['gantt'],
      width: 960,
      height: 300,
    });`

can you help me how to add arg? thank you

**Comment by typpo** [comment]
Hi @aow73320, if you want to pass in a value you can define your chart as a string and then embed the value in the string.  See this example: https://github.com/typpo/google-charts-node/blob/master/examples/chart_as_string.js

For example:

```js
  const myArg = 12345;
  const myOtherArg = [5, 10, 15, 20];
  const drawChart = `
    // Create the data table.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Topping');
    data.addColumn('number', 'Slices');
    data.addRows([
      ['Mushrooms', ${myArg}],
      ['Onions', ${myOtherArg[0]}],
      ['Olives', ${myOtherArg[1]}],
      ['Zucchini', ${myOtherArg[2]}],
      ['Pepperoni', ${myOtherArg[3]}],
    ]);
    // Set chart options
    var options = { title: 'How Much Pizza I Ate Last Night' };
    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  `;
  const image = await GoogleChartsNode.render(drawChart, {
    width: 400,
    height: 300,
  });
```

**Comment by aow73320** [comment]
@typpo wow i got it,it work.
my code can run.
thank you very much.

**Comment by typpo** [comment]
Glad it is working!
