### ISSUE TITLE
How to handle legends in bottom position in image.

### ISSUE THREAD

**Issue by vcomplyRahul** [typpo/google-charts-node#6]
if we use pie, multiple column/ bar chart then legends position in bottom is paginate. so how to show all legends in bottom of image.
[image.pdf](https://github.com/typpo/google-charts-node/files/5560045/image.pdf)

**Comment by typpo** [comment]
Pagination is apparently built-in to the Google Charts library according to a [Google search](https://www.google.com/search?q=google+charts+legend+pagination&oq=google+charts+pagination&aqs=chrome.2.69i57j0i22i30l2j69i64.3375j0j7&sourceid=chrome&ie=UTF-8) and [SO post](https://stackoverflow.com/questions/9802522/is-there-any-way-i-can-avoid-pagination-in-legends-of-a-google-visualisation-cha).

The only way to prevent pagination is to resize the chart or reduce the legend font.  Have you tried either of these?

**Comment by vcomplyRahul** [comment]
Thanks @typpo , working fine
