### ISSUE TITLE
Guage chart is giving not a constructor error

### ISSUE THREAD

**Issue by stardev24** [typpo/google-charts-node#9]
As per the given documentation I have added guage in packages array.
```
     const image = await GoogleChartsNode.render(drawChart, {
                        width: 400,
                        height: 300,
                        packages:['gauge']
          });
```

And draw function is given as 

```
function drawChart() {

    var data = google.visualization.arrayToDataTable([
        ['Label', 'Value'],
        ['Memory', 80]
      ]);

      var options = {
        width: 400, height: 120,
        redFrom: 90, redTo: 100,
        yellowFrom:75, yellowTo: 90,
        minorTicks: 5
      };

	const chart = new google.visualization.Guage(container);
	chart.draw(data, options);
  }
```
But If I try to access it from express server I am getting 

Page error: Error: TypeError: google.visualization.Guage is not a constructor.
Please help

![GuageChartError](https://user-images.githubusercontent.com/13711150/111072683-ae42b180-8501-11eb-8d51-c53bab0301db.png)

**Comment by typpo** [comment]
You're spelling Gauge wrong.  Gauge, not Guage
